version: '2'

services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    image: service-registry:latest
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - docker-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    image: api-gateway:latest
    restart: on-failure
    depends_on:
      - service-registry
      - keycloak
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      docker-network:
        aliases:
          - bank.mydomain.nl

  bank-service:
    build: ./bank-service
    container_name: bank-service
    image: bank-service:latest
    restart: on-failure
    depends_on:
      - service-registry
    ports:
      - "8084:8084"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - docker-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: on-failure
    env_file: ./keycloak.env
    command: start-dev --hostname="keycloak.mydomain.nl"
    depends_on:
      - keycloak_db
    ports:
      - "8080:8080"
    networks:
      docker-network:
        aliases:
          - keycloak.mydomain.nl

  keycloak_db:
    container_name: keycloak_db
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db_volume:/var/lib/postgresql/data
    env_file:
      - ./keycloak-db.env
    networks:
      - docker-network

volumes:
  keycloak_db_volume:
networks:
  docker-network:



