version: '2'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: on-failure
    env_file: ./keycloak.env
    command: start-dev
    depends_on:
      - keycloak_db
    ports:
      - "8083:8080"
    networks:
      - keycloak-network


  keycloak_db:
    container_name: keycloak_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db_volume:/var/lib/postgresql/data
    env_file:
      - ./keycloak-db.env
    networks:
      - keycloak-network

volumes:
  keycloak_db_volume:

networks:
  keycloak-network: