version: '2'

services:
  service-registry:
    container_name: service-registry
    image: service-registry:latest
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      showcase-network:
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    restart: on-failure
    depends_on:
      - service-registry
      - keycloak
    ports:
      - "8082:8082"
    networks:
      showcase-network:
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  bank-service:
    container_name: bank-service
    image: bank-service:latest
    restart: on-failure
    depends_on:
      - service-registry
    ports:
      - "8084:8084"
    networks:
      showcase-network:
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: on-failure
    env_file: ./keycloak.env
    command: start-dev
    depends_on:
      - keycloak_db
    ports:
      - "8083:8080"
    networks:
      showcase-network:

  keycloak_db:
    container_name: keycloak_db
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db_volume:/var/lib/postgresql/data
    env_file:
      - ./keycloak-db.env
    networks:
      showcase-network:


volumes:
  keycloak_db_volume:
networks:
  showcase-network:
    driver: bridge


