server:
  port: 8085

spring:
  kafka:
    consumer:
      bootstrap-servers: kafka-0:9092, kafka-1:9092, kafka-2:9092
      group-id: consumer_group_processed_transactions
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka-0:9092, kafka-1:9092, kafka-2:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
