server:
  port: 8085

spring:
  kafka:
    consumer:
      bootstrap-servers: kafka-0:9092, kafka-1:9092, kafka-2:9092
      group-id: consumer_group_processed_transactions
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      spring:
        kafka:
          consumer:
            properties:
              spring:
                json:
                  trusted:
                    packages=*:
    producer:
      bootstrap-servers: kafka-0:9092, kafka-1:9092, kafka-2:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.showcase.sharedlibrary.serializers.PendingTransactionDtoSerializer

  datasource:
    url: jdbc:postgresql://transaction-db:5432/showcase
    username: showcase-user
    password: showcase-password