server:
  port: 8082
  servlet:
    context-path: /
spring:
  output:
    ansi:
      enabled: always
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
       - TokenRelay=
      routes:
        - id: bank-account-service
          uri: lb://bank-account-service
          predicates:
            - Path=/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: bank-account-service open-api UI
          uri: lb://bank-account-service
          predicates:
            - Path=/bank-account-service/v3/api-docs
            - Method=GET
        - id: transaction-service open-api UI
          uri: lb://transaction-service
          predicates:
            - Path=/transaction-service/v3/api-docs
            - Method=GET




  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/showcase-realm-2
        registration:
          api-gateway:
            provider: keycloak
            client-id: showcase-client-2
            client-secret: DCyddhc3eXAY6cAcRiYdCpUTIHLlQ15Q
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/login/oauth2/code/{registrationId}"
            scope: openid

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /bank-account-service/v3/api-docs
        name: Bank Account Service
      - url: /transaction-service/v3/api-docs
        name: Transaction Service