server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: bank-service
          uri: lb://bank-service
          predicates:
            - Path=/bank-service/**   #matches incoming requests on localhost:8082/bank-service/api

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/showcase-realm-2
        registration:
          api-gateway:
            provider: keycloak
            client-id: showcase-client-2
            client-secret: RUdoTm2ozmG60qGQ9X8srXIJLubg4A6C
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/login/oauth2/code/{registrationId}"
            scope: openid

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
