server:
  port: 8082

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.mydomain.nl:8080/realms/showcase-realm-2
        registration:
          api-gateway: #dit is de registrationId die in sommige url's gebruikt wordt
            provider: keycloak
            client-id: showcase-client-2
            client-secret: RUdoTm2ozmG60qGQ9X8srXIJLubg4A6C
            authorization-grant-type: authorization_code
            redirect-uri: "http://bank.mydomain.nl:8082/login/oauth2/code/api-gateway"
            scope: openid
  cloud:
    gateway:
      routes:
        - id: bank-service
          uri: lb://bank-service
          predicates:
          - Path=/bank-service/**
        - id: bank-account-service
          uri: lb://bank-account-service
          predicates:
            - Path=/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
      #default-filters:
      #  - TokenRelay= #used to forward token in request to downstream resource server

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8081/eureka

#Actuator endpoints
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
