security:
  config:
    keycloak:
      url: http://localhost:8083
      realm: showcase-realm

server:
  port: 8082

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${security.config.keycloak.url}/realms/${security.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${security.config.keycloak.url}/realms/${security.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${security.config.keycloak.url}/realms/${security.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${security.config.keycloak.url}/realms/${security.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          api-gateway:
            provider: keycloak
            client-id: showcase-client-1
            client-secret: Xt4yPIfHzvsYCerA8QiurQVxXGfAPB0p
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${security.config.keycloak.url}/realms/${security.config.keycloak.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: bank-service
          uri: lb://bank-service
          predicates:
            - Path=/bank-service/**   #matches incoming requests on localhost:8082/bank-service/api
          filters:
            - StripPrefix=1   #removes one element on the beginning of the url, which in this case is only "banking-service" from url when sending request downstream. StripPrefix=2 would remove /bank-service/api/ from url when sending downstream.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
