spring:
  application:
    name: bank-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.mydomain.nl:8080/realms/showcase-realm-2
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8081/eureka

info:
  app:
    name: ${spring.application.name}

#Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
