server:
  port: 8086
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/showcase-realm-2
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumer_group_pending_transactions
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.showcase.sharedlibrary.deserializers.PendingTransactionDtoDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.showcase.sharedlibrary.serializers.ProcessedTransactionDtoSerializer
  datasource:
    url: jdbc:postgresql://localhost:5433/bank-account-db
    username: showcase-user
    password: showcase-password

openapi:
  service:
    title: bank-account-service #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://bank.mydomain.nl:8082 #api gateway url
springdoc:
  api-docs:
    path: /bank-account-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /bank-account-service/swagger-ui.html

