server:
  port: 8086

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
  devtools:
    remote:
      proxy:
        port: 5005


  kafka:
    consumer:
      bootstrap-servers: kafka-0:9092, kafka-1:9092, kafka-2:9092
      group-id: consumer_group_processed_transactions
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.showcase.bankaccountservice.kafka.deserialization.PendingTransactionDtoDeserializer
    producer:
      bootstrap-servers: kafka-0:9092, kafka-1:9092, kafka-2:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://bank-account-db:5432/showcase
    username: showcase-user
    password: showcase-password
